### ISSUE TITLE
Cannot spawn children with code 1

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-regressions#1030]
at ChildProcess.<anonymous> (new/node_modules/r2pipe/index.js:274:12)

**Comment by radare** [comment]
So much verbosity.... how to reproduce? :P

**Comment by XVilka** [comment]
It was just latest radare2 + latest radare2-regressions, then `make all`

**Comment by Maijin** [comment]
Missing reproducer, closing and detail on the bug and this issue is r2pipe not r2r likely
