### ISSUE TITLE
EXPECT_ERR64 missing in r2r.js

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-regressions#1126]
EXPECT_ERR64 is missing in r2r.js for transferring remaining tests

**Comment by radare** [comment]
Can we get rid of those expecterr tests?

**Comment by Maijin** [comment]
no they are useful

**Comment by radare** [comment]
How many

**Comment by Maijin** [comment]
there are like 20 or smth

**Comment by Maijin** [comment]
Example, the output of rbin warning to check if the binary have no entrypoint detected that's important etc.

**Comment by Maijin** [comment]
it's supported now
