### ISSUE TITLE
cannot run new db tests

### ISSUE THREAD

**Issue by fenugrec** [radare/radare2-regressions#1149]
```$ cd new
$ time
real    0m0.000s
user    0m0.000s
sys     0m0.000s
$ make run
time node bin/r2r.js
make: time: Command not found
$
$
$ time node bin/r2r.js 
module.js:557
    throw err;
    ^

Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/q/d/r2/radare2-regressions/new/index.js:1:74)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)

real    0m0.151s
user    0m0.150s
sys     0m0.000s
```

**Comment by Maijin** [comment]
Without installing the required stuff. Use make js-tests at root or use npm install in the new/ directory before running bin/r2r.js

**Comment by fenugrec** [comment]
Thanks. I didn't see that mentioned in any of the readme's. Some progress
```$ make js-tests
cd new && npm install
npm WARN r2r@0.1.0 No repository field.

up to date in 2.005s
cd new && node bin/r2r.js
[**]                    db/cmd/0000   OK    0 BR    1 XX    0 FX    0
~/d/r2/radare2-regressions/new/index.js:385
          throw new Error('Invalid database, key =(', k, ')');
          ^

Error: Invalid database, key =(
    at NewRegressions.runTests (~/d/r2/radare2-regressions/new/index.js:385:17)
    at Gunzip.zlib.gunzip [as cb] (~/d/r2/radare2-regressions/new/index.js:408:14)
    at Gunzip.zlibBufferOnError (zlib.js:93:8)
    at Gunzip.emit (events.js:160:13)
    at Zlib.zlibOnError [as onerror] (zlib.js:145:8)
make: *** [Makefile:218: js-tests] Error 1
```
So I'm missing something else ?

**Comment by Maijin** [comment]
probably mega old node, I'm using v9.3.0 and it works fine

**Comment by fenugrec** [comment]
node v9.4.0 !!

**Comment by Maijin** [comment]
my second guess, when you ran makefile in the "new" folder and generate some garbage, clean everything or clone a new r2r and try make js-tests again alvaro already had this issue

**Comment by Maijin** [comment]
I cleaned the makefile all rule to avoid this happens again

**Comment by fenugrec** [comment]
Correct. There was some stuff leftover due to .gitignore that I hadn't removed. Tests are running now, thanks.

**Comment by radare** [comment]
All node programs work in the same way. I dont see gnu programs explaining how to run autotools or rust with cargo, etc

**Comment by fenugrec** [comment]
> gnu programs explaining how to run autotools

well they do - the INSTALL file is created automatically IIRC if you run one of the autotools with "--add-missing"  when preparing a tarball release. I haven't worked with autotools in a while though, I avoid it when I can.
Anyway, this issue is closed, but I still think the node testsuite needs a bit of improvement and/or documentation. Yes, I know you guys hate documentation.

**Comment by radare** [comment]
Yes it needs lot of improvements for users and devs. And also needs all old tests to be imported. The benefits are quite big.

PRs are appreciated, as long as 99% of the time this is only executed by travis and i have other priorities like improving r2. I spent some random time to r2r when i need it, so please feel free to send your fixes if u find any issue you can fix. I’ll do my best to improve the new r2r
