### ISSUE TITLE
Create test cases for ALL ioli crackmes

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#116]

**Comment by Maijin** [comment]
@radare what kind of testcase ? Corkami seems more appropriate for testcase than IOLI.

**Comment by radare** [comment]
Check if good/bad boy strings are recognized. Jump in the middle stuff, etc. I would like @poliva to help on that coz hes the author and can provide more ideas on it

**Comment by Maijin** [comment]
done.
