### ISSUE TITLE
Test r_sys_* functions

### ISSUE THREAD

**Issue by giuscri** [radare/radare2-regressions#1209]
To my understanding `mkdir`, `cat`, `ls`, ... commands are not tested.

Example of a bug: https://github.com/radare/radare2/issues/9521

Where should these tests be added?

**Comment by radare** [comment]
New/db/cmd/cmd_ownshell for example

**Comment by Maijin** [comment]
that sounds good

**Comment by giuscri** [comment]
this is now tested in new/db/cmd/cmd_ownshell
