### ISSUE TITLE
Move current tests into old/

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#1432]
new/ is the current, so its no longer new, anyway i prefer to have each testsuite in a separate directory.

* new/
* old/
* unit/
* r2go

...

**Comment by radare** [comment]
cc @Maijin

**Comment by Maijin** [comment]
ok done, sorry for restarting the builds, had to do some tweaks, there are many hidden places with paths

**Comment by Maijin** [comment]
For r2go, @wargio needs to fix the OSX output before we can do any integration
