### ISSUE TITLE
Add test clase for DEX/Dalvik disassembling new-instance and invoke-*

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#155]
to verify that symbol resolution works in `pd`

**Comment by Maijin** [comment]
* https://github.com/radare/radare2-regressions/blob/master/t.asm/dalvik/dalvik#L128-L137
* https://github.com/radare/radare2-regressions/blob/master/t.asm/dalvik/dalvik#L58

^<- No tests yet related to the symbol resolution

**Comment by h4ng3r** [comment]
Fixed in https://github.com/radare/radare2-regressions/pull/704. Can I close it @Maijin ?

**Comment by Maijin** [comment]
Well yes, no need for my approval for that :)

**Comment by h4ng3r** [comment]
Not approval, just your blessing ;)
