### ISSUE TITLE
Add tests for Signatures  related commands and tools

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-regressions#166]
* [x] Flirt
* [x] Zsignature

**Comment by radare** [comment]
wasnt this jn's rsoc?

**Comment by Maijin** [comment]
@radare @jfrankowski no ? But whatever must be done

**Comment by Maijin** [comment]
* http://radare.today/zignatures/

**Comment by radare** [comment]
oh yes sorry s/jn/jf/. indeed

**Comment by Maijin** [comment]
Already regressions on zsignature when trying command from the article...

**Comment by radare** [comment]
awesome! :D

**Comment by Maijin** [comment]
:(

**Comment by radare** [comment]
Canu provide details of that? Or at least a test?

**Comment by Maijin** [comment]
Test is here, and I can't reproduce the result described here http://radare.today/zignatures/

**Comment by Maijin** [comment]
More test to be added by @XVilka see https://github.com/radare/radare2-regressions

**Comment by radare** [comment]
THere are already some zignature tests and ill add some more now
