### ISSUE TITLE
Allow python based tests

### ISSUE THREAD

**Issue by bannsec** [radare/radare2-regressions#1717]
For those of us who really are not so into C/js, it would be nice if we could contribute tests using python. My thinking is the tests would probably be either r2pipe based, or depending on the issue, perhaps utilize CDLL/CFFI.

Really the main ask is just a way to add python test files that will be run, similar to how you do it for C and js.

**Comment by Maijin** [comment]
I don't see the point of this. C files are for unit-testing. The other tests aren't javascript, just pure r2 commands so it's basically the same as running r2pipe.

**Comment by XVilka** [comment]
@bannsec see https://github.com/radare/radare2-bindings/issues/167
