### ISSUE TITLE
dwarf tests

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#174]
current output looks good to me, would be good to review it again and mark them as fixed (updating the disasm output)

**Comment by Maijin** [comment]
Travis doesn't like the way the test is made

**Comment by radare** [comment]
i know, the tests are not passing, they need to be reviewed and updated the output because its now showing fullpath to file and the `pd` output is a bit different now.

**Comment by Maijin** [comment]
Those tests pass now.
