### ISSUE TITLE
t.archos silently fails to run when doing "make all" in linux

### ISSUE THREAD

**Issue by dequis** [radare/radare2-regressions#217]
(Continuing from https://github.com/radare/radare2/pull/3193#issuecomment-136196511 )

`t.archos` isn't running in linux because the makefile expects a directory called `Linux-x86_64` instead of just `Linux`

```
$ make
[ -d "Linux-x86_64" ] && ( cd .. && sh run_tests.sh t.archos/Linux-x86_64 )
Makefile:4: recipe for target 'all' failed
make: *** [all] Error 1
```

(edited the makefile so that it wouldn't fail silently)

Pancake suggested `sh run_tests.sh t.archos`, but that runs both darwin and linux tests, and the darwin ones vomit errors, unsurprisingly.

`t.archos` is the only one in `make all` which runs with `@$(MAKE) -C t.archos`, instead of `@sh run_tests.sh t.archos`. Git blame points at PR #73 - which makes sense given that the makefile filters the tests and the shell script doesn't.

Fix idea:

```
ln -s Linux Linux-x86_64
ln -s Linux Linux-i686
```

But that would make `sh run_tests.sh t.archos` run the linux tests three times (and the darwin ones too)

**Comment by radare** [comment]
Yeah my command should fail. U should use make or specify the target archos subdir

**Comment by dequis** [comment]
@Maijin wait, why? the issue is still present, it still fails silently when running "make all" in linux, but works in darwin.

**Comment by Maijin** [comment]
Sorry I though @radare answered your question :)

**Comment by Maijin** [comment]
New mechanism, need to be retested. Closing here
