### ISSUE TITLE
unit tests for r_* utilities

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-regressions#242]
rregex, string, etc. should have unit tests. https://github.com/radare/radare2/issues/3221

**Comment by crowell** [comment]
https://github.com/radare/radare2-regressions/tree/master/unit

we have starting unit tests here. we should do a fixit day some time to add them all.

**Comment by Maijin** [comment]
@crowell Also see existing that just need to be moved https://github.com/radare/radare2/tree/master/libr/util/t

**Comment by Maijin** [comment]
See https://github.com/radare/radare2-regressions/issues/492
