### ISSUE TITLE
kcov data for unit tests

### ISSUE THREAD

**Issue by crowell** [radare/radare2-regressions#245]
kcov works pretty well for the unit tests to show coverage. for the system tests, i think kcov is too slow, and the gcov compiled binaries segfault still.

**Comment by crowell** [comment]
output from current unit tests http://toonces.cat/kcov/

@Maijin would it be easy to get some sort of useful output from travis for the coverage? or this is probably better suited for jenkins to run a job and keep the kcov data updated on the site somewhere.

**Comment by crowell** [comment]
yeah, there's a jenkins plugin guy here https://simonkagstrom.github.io/kcov/  let's use this.

**Comment by crowell** [comment]
actually, it can run with travis and coveralls, even better

`kcov --coveralls-id=$TRAVIS_JOB_ID /path/to/outdir executable`

**Comment by Maijin** [comment]
@crowell yeah :D that would be super cool and useful
