### ISSUE TITLE
Better Tests for ESIL

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-regressions#246]
From @sushant94 "The idea is to have better tests for x86 and x86_64 esil by comparing the ESIL register and memory states vs. a run of the same binary inside gdb. This will help us catch bugs that maybe difficult to find manually. Also, can reduce the amount of time spent in writing tests as the output is compared against a run rather than static, hardcoded values."

https://github.com/radare/radare2/issues/3639

**Comment by radare** [comment]
What about using unicorn instead of gdb? Gdb/lldb scripting sucks and its not portable.

**Comment by sushant94** [comment]
I thought about this option. But this would mean that we trust unicorns
emulation and there are no bugs in unicorn.

**Comment by Maijin** [comment]
Dup
