### ISSUE TITLE
RISC-V tests

### ISSUE THREAD

**Issue by XVilka** [radare/radare2-regressions#247]
All opcodes to test, add in https://github.com/radare/radare2-regressions/tree/master/t.asm

**Comment by XVilka** [comment]
@q6r what do you think about this one?

**Comment by q6r** [comment]
Sounds good, but I can't do it now :(

**Comment by Maijin** [comment]
@q6r can't you generate some? So it will avoid your stuff go in r2-extras because dead/not-working after a while ?

**Comment by Maijin** [comment]
@q6r ping ?
