### ISSUE TITLE
Add tests for t commands

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-regressions#287]
https://github.com/radare/radare2/issues/2101

* [x] t                  List all loaded types
* [x] t <type>           Show type in 'pf' syntax
* [x] t*                 List types info in r2 commands (https://github.com/radare/radare2/issues/3925)
* [x] t- <name>          Delete types by its name
* [x] t-*                Remove all types (https://github.com/radare/radare2/issues/3932)
* [x] tb <enum> <value>  Show matching enum bitfield for given number
* [x] te <enum> <value>  Show name for given enum number
* [x] td <string>        Load types from string
* [x] tf <addr>          View linked type at given address
* [ ] tl[?]              Show/Link type to a address
* [x] to -               Open cfg.editor to load types
* [x] to <path>          Load types from C header file
* [x] tk <sdb-query>     Perform sdb query
* [ ] ts <k>=<v>         Set fields at curseek linked type

**Comment by Maijin** [comment]
Will Need obviously more than one test :100:

**Comment by oddcoder** [comment]
td- is redundant  t- performs the same functionality

**Comment by Maijin** [comment]
@radare ^

**Comment by radare** [comment]
agree, it was there just for consistency

if you can define with td, you can undefine with td-

but t- seems also a valid way to remove a type for me, what do you think?

**Comment by oddcoder** [comment]
@Maijin t* and ts are done ,`tl` is not yet though it is checked
