### ISSUE TITLE
Add tests for rahash2 -E

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#324]
encrypt and such, i'll try to find some time to add AES support too

**Comment by Maijin** [comment]
Yes also going to create an issue with more ideas

**Comment by radare** [comment]
We need a command in r2 for that

i moved woD and woO to wop[DO].. so woE and woD will be to encrypt and decrypt

**Comment by radare** [comment]
the commit in r2 is ready and tested inlocal so it works. but we should have tests for this can you write them?

**Comment by Maijin** [comment]
woD doesn't work yet https://github.com/radare/radare2-regressions/commit/6e471f2c9744737b0db00b79ab2858e3c1a0ab91
