### ISSUE TITLE
Broken testsuite

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#428]
Now the testuite behaves wrongly after https://github.com/radare/radare2-regressions/commit/4c179bcbe611b9f8fddf814e0309f53e2ff689cd

i have observed the following issues:

* the diff when a test fails is inverted
* segfaults no longer appear

**Comment by jduck** [comment]
I had some issues myself while putting these PRs together. I thought they were gone, but apparently not. We need some tests for the tests framework LOL.

**Comment by jduck** [comment]
BTW this commit looks like the wrong one to blame. I'd guess the latest merge could actually cause the issue though.

**Comment by jduck** [comment]
I'm not seeing how segfaults ever appeared -- even if I go back to 0.10.2 of r2r.

**Comment by jduck** [comment]
I guess segfault not showing up must have been an r2 change, not related to r2r at all. We are not running radiff2 directly. Instead, it's ran via radare2's !! command.
