### ISSUE TITLE
Automated bisect on specific broken tests

### ISSUE THREAD

**Issue by radare** [radare/radare2-regressions#46]
We need jenkins to bisect r2 in order to identify who and where broke a specific test. This will speedup fixing regressions as long as we will directly see the changing code that affects the test.

protip: using a learning machine we can use this data (which files affect which tests) to determine specific directory coverage automatically without having to do it manually.

**Comment by Maijin** [comment]
This is longtime runner closing it, we know that's a nice to have, issue is useless.
