### ISSUE TITLE
Add ESIL crackme example

### ISSUE THREAD

**Issue by Maijin** [radare/radare2-regressions#499]
@monosource  can you add an esil test case for https://monosource.github.io/2016/08/trendmicro-re100 ?

**Comment by monosource** [comment]
@Maijin You mean reconstruct the entire solution in a test case where the expected output is the flag?

**Comment by Maijin** [comment]
yes

**Comment by monosource** [comment]
@Maijin fixed with #501

**Comment by Maijin** [comment]
Add "fix #XXX" in the commit message or title next time
