### ISSUE TITLE
cmd_pf skips all remaining tests

### ISSUE THREAD

**Issue by bluec0re** [radare/radare2-regressions#542]
https://github.com/radare/radare2-regressions/blob/master/t/cmd_pf#L548 skips not only the remaining tests in the file, but also all following tests without any warning.

I guess it's a mistake or is there any reason for this?

**Comment by Maijin** [comment]
Yep this must be removed.

**Comment by Maijin** [comment]
Yep removed, and as you can see XX tests were hidden :( Thanks reporting this ! Time to fix now !
