### ISSUE TITLE
Ensure that we are running ALL the tests in travis

### ISSUE THREAD

**Issue by trufae** [radare/radare2-regressions#577]
looks like the debrujn ones are not executed... maybe some others.. are we running the debugger tests too?..

**Comment by XVilka** [comment]
AFAIR debugger tests can't be run on Travis-CI.

**Comment by Maijin** [comment]
Debugger tests can't be run on travis, this is known limitation.

**Comment by Maijin** [comment]
Debruijin test is executed:
![image](https://cloud.githubusercontent.com/assets/1408600/19080928/d8842a62-8a58-11e6-816c-e289a69419bf.png)
But doesn't make the CI fail

**Comment by Maijin** [comment]
@crowell can you check why your unit tests aren't producing error code when failing ?

**Comment by radare** [comment]
I think @ret2libc did

**Comment by ret2libc** [comment]
I did it for the unit test part.

**Comment by Maijin** [comment]
Well that's all needed, for debugger, those need to be executed on jenkins

**Comment by Maijin** [comment]
and there is already a jenkins rule for that cc @XVilka
