### ISSUE TITLE
cmd_json fails

### ISSUE THREAD

**Issue by gipi** [radare/radare2-regressions#633]
The array initialization defined as

```
    declare -a arr=("aa ; pdfj"
```

in ``t/cmd_json.sh`` throws an error because ``sh`` doesn't support it (I'm on an Ubuntu 14.04). Launching with ``bash`` all is fine.

**Comment by radare** [comment]
who the hell wrote this bashism??!?

**Comment by radare** [comment]
oh @maijin :(

**Comment by radare** [comment]
there are more issues in this script. fixing,. will commit soon(R)

**Comment by Maijin** [comment]
kk cool sorry for that
