### ISSUE TITLE
pdf fails without apparent reason

### ISSUE THREAD

**Issue by gipi** [radare/radare2-regressions#634]
There are two ``exit 1`` at the end of ``t/pdf`` that seems to cause the tests to stop as described below:
```
$ make
 [...]
[OK]  5  pdf: pdf dwarf abspath
[OK]  6  pdf: pdf dwarf without dir.source  
make: *** [do] Error 1
```

I don't know if this is expected, removing the last two lines from the file makes the tests run and complete.

I can send the patch eventually.

**Comment by alvarofe** [comment]
fixed. Thx
