### ISSUE TITLE
t/cmd_write: wx 0x should behave as wv is broken

### ISSUE THREAD

**Issue by SchumBlubBlub** [radare/radare2-regressions#705]
https://github.com/radare/radare2-regressions/pull/680

```
././cmd_write: line 228: cd: t/.tmp: No such file or directory
$ ls -1 t/b.exe.new  
t/b.exe.new
``` 

cc @CodingFree

**Comment by CodingFree** [comment]
Actually, it is "wci should commit the changes to the file". Lets continue at #680, please.

**Comment by radare** [comment]
in wx there's no endian to honor. in wv it does. so imho doing wx 0x... is wrong and it shouldnt be permitted. right now we just ignore the 0x. so imho your reasoning is wrong and the test is wrong too

**Comment by radare** [comment]
@CodingFree unrelated?
